// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using linkHomeApp.Data;

#nullable disable

namespace linkHomeApp.Migrations
{
    [DbContext(typeof(linkHomeContext))]
    partial class linkHomeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("linkHomeApp.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "News"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Social"
                        },
                        new
                        {
                            Id = 3,
                            Title = "Education"
                        },
                        new
                        {
                            Id = 4,
                            Title = "Entertainment"
                        });
                });

            modelBuilder.Entity("linkHomeApp.Models.Link", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Pinned")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Links");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Label = "CNN",
                            Pinned = true,
                            Url = "https://www.cnn.com"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Label = "BBC",
                            Pinned = false,
                            Url = "https://www.bbc.com"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Label = "Reuters",
                            Pinned = false,
                            Url = "https://www.reuters.com"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Label = "Facebook",
                            Pinned = true,
                            Url = "https://www.facebook.com"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Label = "Twitter",
                            Pinned = false,
                            Url = "https://www.twitter.com"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Label = "Instagram",
                            Pinned = false,
                            Url = "https://www.instagram.com"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Label = "Khan Academy",
                            Pinned = false,
                            Url = "https://www.khanacademy.org"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Label = "Coursera",
                            Pinned = false,
                            Url = "https://www.coursera.org"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Label = "edX",
                            Pinned = false,
                            Url = "https://www.edx.org"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            Label = "YouTube",
                            Pinned = true,
                            Url = "https://www.youtube.com"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 4,
                            Label = "Netflix",
                            Pinned = false,
                            Url = "https://www.netflix.com"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            Label = "Spotify",
                            Pinned = false,
                            Url = "https://www.spotify.com"
                        });
                });

            modelBuilder.Entity("linkHomeApp.Models.Link", b =>
                {
                    b.HasOne("linkHomeApp.Models.Category", "Category")
                        .WithMany("Links")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("linkHomeApp.Models.Category", b =>
                {
                    b.Navigation("Links");
                });
#pragma warning restore 612, 618
        }
    }
}
